name: Robô de Mapeamento Escolar (Scraper)

# Define QUANDO o robô vai rodar
on:
  schedule:
    # Roda automaticamente todos os dias às 08:00 UTC (05:00 horário de Brasília)
    - cron: '0 8 * * *'
  
  # Este comando cria um botão no GitHub para você rodar manualmente quando quiser
  workflow_dispatch: 

# IMPORTANTE: Dá permissão para o robô poder salvar o novo CSV dentro do repositório
permissions:
  contents: write

jobs:
  executar-robo:
    runs-on: ubuntu-latest # O GitHub empresta um computador com Linux (grátis) para rodar

    steps:
      # 1. Puxa os arquivos (Atualizado para v4 para sumir o aviso amarelo)
      - name: Acessar arquivos do repositório
        uses: actions/checkout@v4

      # 2. Instala o Python (Atualizado para v5)
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala as dependências
      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 pandas

      # 4. Roda o código Web Scraping
      - name: Executar o Web Scraping
        run: python scraper.py

      # 5. Salva os resultados no repositório
      - name: Salvar resultados no repositório
        run: |
          git config --global user.name 'Robo Web Scraper'
          git config --global user.email 'acoes@github.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Atualizando dados das escolas"
          git push
